apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: mysql-connection
spec: 
  acessModes:
    - ReadWriteOnce
  resources:
    requests:
    storage: 10Gi
  storageClassName: standard-rwo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: bzrr0/projeto-database:1.1
        args:
        - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        
        volumeMounts:
        - name: mysql-connection
          mountPath: /var/lib/mysql/
        volumes: 
        - name: mysql-connection
          persistentVolumeClaim:
            claimName: mysql-connection

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: php
  labels:
    app: php
spec: 
  replicas: 6
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec: 
      containers:
      - name: php
        image: bzrr0/projeto-backend:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
